blank_issues_enabled: true
contact_links:
  - name: Stackduck support
    url: https://github.com/nodedots/stackduck/discussions
    about: Ask a usage question or discuss an idea with the community.
